project_id = "vnfgotlhocfxptkswgnu"

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.apply-promo-code]
verify_jwt = false
